### ISSUE TITLE
Create an easier to use settings system

### ISSUE THREAD

**Issue by frankie-tech** [excelerondesign/whc#10]
Using the script tag is clunky and annoying, its also easy to forget

the new settings system could come with defaults, a mergeable global object like [lazySizes](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L14-L47), and still take advantage of dataset options on html elements

- [x] Defaults
- [x] Merge-able global object
- [x] Still use dataset on html elements

**Comment by gingerchew** [comment]
I reopened this issue since a better solution was created in #34 with adding the data attributes to the form element instead of the script tag. Need to merge this into the develop branch
