### ISSUE TITLE
Does it make sense to create a thin PubSub wrapper instead of exposing CustomEvents?

### ISSUE THREAD

**Issue by frankie-tech** [excelerondesign/whc#8]
I'm not looking to add dependencies, but [this](https://github.com/developit/mitt) is a good example of what I mean.

Instead of listening for events on the `window` or `document` or `form`, you instead add functions to a listener. When that listener is emitted, your function will run.

```js
function runMySpecialFunction() {
	console.log('🎉🎉🎉');
}

function logExtraStuff(data) {
	console.log("Who are you dating?", data.name);
}

on('WHC:Submit', runMySpecialFunction);

// Later on

emit('WHC:Submit', { name: 'Joe Mama!' });

// 🎉🎉🎉

// Who are you dating? Joe Mama!

off('WHC:Submit', runMySpecialFunction);

emit('WHC:Submit');

// silence is golden...
```

This is a more accepted pattern and might even be simpler to build into the plugin

## Tentative To-Do

- [x] CustomEvents function
- [x] List events
	- [x] Progress
	- [x] Verified
	- [x] Error
	- [x] Hash Complete?
		- This may not be possible with Rollup and Workers currently
- [x] add suggested content from #6 
	- see comments below

**Comment by frankie-tech** [comment]
I'm going to make a simple `CustomEvents` system based off of what CFerdinandi has done with [Bouncer](https://github.com/cferdinandi/bouncer/blob/master/src/js/bouncer/bouncer.js#L125+132).

It seems like this may be a fair bit more performant and accessible. If there are size concerns (exceeding the 4kb limit) we can reassess.

- [ ] CustomEvents function
- [ ] List events
	- [ ] Progress
	- [ ] Verified
	- [ ] Error
	- [ ] Hash Complete?
		- This may not be possible with Rollup and Workers currently

**Comment by frankie-tech** [comment]
Some event structure from #6 

Event Structure: "WHC:" Start|Update|Error|Complete
Details:

- Start:
```js
{
	"form": "formElement",
	"time": "timeSentWithRequest", // (in ms)
	"timeLocale": "localizedTime?", // probably not gonna happen
}
```

- Update:
```js
{
	"form": "formElement",
	"time": "timeOfUpdate", // (in ms)
	"progress": "progressReturnedWithUpdate"
}
```

- Error:
```js
{
	"form": "formElement",
	"time": "timeOfError", // (in ms)
	"error": "errorJSON" // Need to force an error message to see what the API returns
}
```

- Complete:
```js
{
	"form": "formElement",
    "time": "timeOfCompletion",
	"verification": "verificationJson",
	"emoji": "🎉"
}
```

**Comment by gingerchew** [comment]
### This is being reopened

Issue I'm having is with justifying the Pub/Sub model. It doesn't seem to work as it is only beneficial in the case of debugging. More patterns need to be assessed. I'm opening a new issue and going to begin collecting resources.
