### ISSUE TITLE
Expose public functions

### ISSUE THREAD

**Issue by frankie-tech** [excelerondesign/whc#9]
I'm trying to think, there might be some merit for public functions like re-verifying forms

~~Expose a global object~~
*Nothing worth exposing to a global object other than the FF Worker bug*
~~Proxy~~
*Nothing to proxy*
~~Track each form~~
*Taken care of by CustomEvents*
~~Expose instance in global~~
*Doesn't make sense for the next version*
- [ ] Re-verify form

**Comment by gingerchew** [comment]
I'm cancelling this. Doesn't make any sense after more updates
